/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/game-board/gameBoardModel.glb 
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/game-board/gameBoardModel.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Plane003" position={[0, 32.809, -2.844]} rotation={[0, 0, -Math.PI / 2]} />
        <group name="Buraco" scale={[1, 1.477, 1.824]} />
        <mesh
          name="Peça"
          geometry={nodes.Peça.geometry}
          material={materials["Material.002"]}
          position={[-0.209, 10.787, -49.886]}
          scale={[8.723, 1.477, 1.824]}
        />
        <mesh
          name="Peça021"
          geometry={nodes.Peça021.geometry}
          material={materials["Material.004"]}
          position={[-0.209, 10.787, -58.368]}
          scale={[8.723, 1.477, 1.824]}
        />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials.Material}
          position={[0, -1.477, -37.844]}
        />
        <mesh
          name="Plane001"
          geometry={nodes.Plane001.geometry}
          material={nodes.Plane001.material}
          position={[-25.587, 1.544, -2.844]}
        />
        <mesh
          name="Lateral001"
          geometry={nodes.Lateral001.geometry}
          material={nodes.Lateral001.material}
          position={[0, -1.477, 0]}
        />
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
          scale={[1, 1.477, 1.824]}
        />
        <mesh
          name="Peça006"
          geometry={nodes.Peça006.geometry}
          material={nodes.Peça006.material}
          position={[9.723, 54.238, 23.406]}
          scale={[8.723, 1.477, 1.824]}
        />
        <mesh
          name="Buraco_2"
          geometry={nodes.Buraco_2.geometry}
          material={nodes.Buraco_2.material}
          scale={[1, 1.477, 1.824]}
        />
        <mesh
          name="Buraco001"
          geometry={nodes.Buraco001.geometry}
          material={nodes.Buraco001.material}
          scale={[1, 1.477, 1.824]}
        />
        <mesh
          name="Peça_Vermelha"
          geometry={nodes.Peça_Vermelha.geometry}
          material={materials["Material.003"]}
          position={[-0.041, 28.525, 51.41]}
          scale={[8.723, 1.477, 1.824]}
        >
          <mesh
            name="Peça002"
            geometry={nodes.Peça002.geometry}
            material={materials["Material.003"]}
            position={[0, -11.962, -20.062]}
          />
          <mesh
            name="Peça003"
            geometry={nodes.Peça003.geometry}
            material={materials["Material.003"]}
            position={[0, -12.003, -29.769]}
          />
          <mesh
            name="Peça005"
            geometry={nodes.Peça005.geometry}
            material={materials["Material.003"]}
            position={[0, -11.962, -24.868]}
          />
          <mesh
            name="Peça007"
            geometry={nodes.Peça007.geometry}
            material={materials["Material.003"]}
            position={[0, -6.025, -24.868]}
          />
          <mesh
            name="Peça010"
            geometry={nodes.Peça010.geometry}
            material={materials["Material.003"]}
            position={[0, -5.9, -34.723]}
          />
          <mesh
            name="Peça012"
            geometry={nodes.Peça012.geometry}
            material={materials["Material.003"]}
            position={[0, 0, -29.91]}
          />
          <mesh
            name="Peça018"
            geometry={nodes.Peça018.geometry}
            material={materials["Material.003"]}
            position={[-1.454, -24.699, -24.119]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[5.907, 0.169, 1]}
          />
          <mesh
            name="Peça019"
            geometry={nodes.Peça019.geometry}
            material={materials["Material.003"]}
            position={[-1.454, -24.699, -17.903]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[5.907, 0.169, 1]}
          />
          <mesh
            name="Peça020"
            geometry={nodes.Peça020.geometry}
            material={materials["Material.003"]}
            position={[-0.862, -24.699, -12.844]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[5.907, 0.169, 1]}
          />
        </mesh>
        <mesh
          name="Peça_Amarela"
          geometry={nodes.Peça_Amarela.geometry}
          material={materials["Material.002"]}
          position={[-0.209, 37.008, 50.179]}
          scale={[8.723, 1.477, 1.824]}
        >
          <mesh
            name="Peça001"
            geometry={nodes.Peça001.geometry}
            material={materials["Material.002"]}
            position={[0, -17.756, -14.676]}
          />
          <mesh
            name="Peça004"
            geometry={nodes.Peça004.geometry}
            material={materials["Material.002"]}
            position={[0, -11.733, -19.362]}
          />
          <mesh
            name="Peça008"
            geometry={nodes.Peça008.geometry}
            material={materials["Material.002"]}
            position={[0, -5.796, -24.284]}
          />
          <mesh
            name="Peça009"
            geometry={nodes.Peça009.geometry}
            material={materials["Material.002"]}
            position={[0, 0, -29.125]}
          />
          <mesh
            name="Peça011"
            geometry={nodes.Peça011.geometry}
            material={materials["Material.002"]}
            position={[0, -11.807, -29.125]}
          />
          <mesh
            name="Peça013"
            geometry={nodes.Peça013.geometry}
            material={materials["Material.002"]}
            position={[-1.435, -30.443, -29.065]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[5.907, 0.169, 1]}
          />
          <mesh
            name="Peça014"
            geometry={nodes.Peça014.geometry}
            material={materials["Material.002"]}
            position={[-2.12, -30.443, -29.065]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[5.907, 0.169, 1]}
          />
          <mesh
            name="Peça015"
            geometry={nodes.Peça015.geometry}
            material={materials["Material.002"]}
            position={[-2.12, -30.443, -20.661]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[5.907, 0.169, 1]}
          />
          <mesh
            name="Peça016"
            geometry={nodes.Peça016.geometry}
            material={materials["Material.002"]}
            position={[-1.402, -30.443, -38.349]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[5.907, 0.169, 1]}
          />
          <mesh
            name="Peça017"
            geometry={nodes.Peça017.geometry}
            material={materials["Material.002"]}
            position={[-0.973, -30.443, -33.227]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[5.907, 0.169, 1]}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/game-board/gameBoardModel.glb");
